# Generated by Django 4.2.30 on 2026-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongregationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_preacher', models.CharField(max_length=255)),
                ('name_of_village', models.CharField(max_length=255)),
                ('month_of_reporting', models.CharField(max_length=50)),
                ('bible_studies_meetings_count', models.IntegerField(default=0)),
                ('baptisms_count', models.IntegerField(default=0)),
                ('names_of_baptized_people', models.TextField(blank=True)),
                ('church_members_count', models.IntegerField(default=0)),
                ('benevolent_aid_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_weekly_giving', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('church_photo', models.ImageField(upload_to='church_photos/')),
                ('inspiring_stories', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KCMBIFieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(max_length=255)),
                ('meeting_date_time', models.DateTimeField()),
                ('kcmbi_number', models.CharField(max_length=50)),
                ('class_topic_or_text', models.CharField(max_length=255)),
                ('meeting_address', models.TextField()),
                ('preachers_in_attendance', models.TextField(blank=True)),
                ('meeting_photo', models.ImageField(upload_to='meeting_photos/')),
                ('group_concerns', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreacherPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_preacher', models.CharField(max_length=255)),
                ('team_leader_name', models.CharField(max_length=255)),
                ('cell_number', models.CharField(max_length=20)),
                ('preacher_address', models.TextField()),
                ('congregation_address', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('aadhar_card_photo', models.ImageField(upload_to='aadhar_photos/')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('preacher_photo', models.ImageField(upload_to='preacher_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeaderPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('cell_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('aadhar_card_photo', models.ImageField(upload_to='leader_aadhar/')),
                ('number_of_kcmbis_submitting', models.IntegerField(default=0)),
                ('team_leader_photo', models.ImageField(upload_to='leader_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
