# Generated by Django 4.2.30 on 2026-06-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_preacherpersonalinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregationupdate',
            name='preacher_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congregation_updates', to='reports.preacherpersonalinfo'),
        ),
        migrations.AddField(
            model_name='kcmbifieldreport',
            name='team_leader_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reports', to='reports.teamleaderpersonaldata'),
        ),
        migrations.AddField(
            model_name='preacherpersonalinfo',
            name='team_leader_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preachers', to='reports.teamleaderpersonaldata'),
        ),
    ]
