# Generated by Django 4.2.30 on 2026-06-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_congregationupdate_preacher_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.CharField(max_length=50)),
                ('zone_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='reports.teamleaderpersonaldata')),
            ],
            options={
                'ordering': ['zone_number'],
            },
        ),
        migrations.AddField(
            model_name='congregationupdate',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congregation_updates', to='reports.zone'),
        ),
        migrations.AddField(
            model_name='preacherpersonalinfo',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preachers', to='reports.zone'),
        ),
    ]
