# Generated by Django 4.2.30 on 2026-06-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_zone_congregationupdate_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcmbifieldreport',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reports', to='reports.zone'),
        ),
    ]
