# Generated by Django 4.2.30 on 2026-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_kcmbifieldreport_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregationupdate',
            name='other_photo',
            field=models.ImageField(blank=True, upload_to='other_photos/'),
        ),
    ]
