# Generated by Django 6.0.6 on 2026-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_congregationupdate_other_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacherpersonalinfo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preacherpersonalinfo',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
